Add totem pop counter to nametags
lambda-client/lambda-legacy pull request #117
Opened 2021-06-13 23:03 UTC by ToxicAven

Probably a better way to do this, but it functions.

2021-06-14 01:01 UTC, Xiaro commented on src/main/kotlin/com/lambda/client/module/modules/combat/TotemPopCounter.kt
> +    val popCountMap = WeakHashMap<EntityPlayer, Int>().synchronized()
Move this into a Manager unless it wont do anything when the module is disabled

2021-06-14 01:05 UTC, Xiaro requested changes

2021-06-14 01:05 UTC, Xiaro commented on src/main/kotlin/com/lambda/client/module/modules/combat/TotemPopCounter.kt
> +    val popCountMap = WeakHashMap<EntityPlayer, Int>().synchronized()
Move this into a Manager unless it wont do anything when the module is disabled

2021-06-14 01:05 UTC, Xiaro commented on src/main/kotlin/com/lambda/client/module/modules/render/Nametags.kt
> +           val pluralPops = if (TotemPopCounter.popCountMap[entity] == 1) "pop" else "pops"
Store the number in a varible instead of getting it repeatly and doing unsafe null check

2021-06-24 15:18 UTC, ToxicAven commented
I need to take a short break from lambda development, so this pull will stagnate for a bit longer.

2021-10-04 18:41 UTC, closed without merging