Add live stock ticker
lambda-client/lambda-legacy pull request #190
Opened 2021-11-18 20:27 UTC by ItCameFr0mMars

**Describe the pull**
Adds a module that lets you monitor the price of a stock in realtime

**Describe how this pull is helpful**
cool gui module

**Additional context**
thx lambda discord for helping

2021-11-18 20:33 UTC, ItCameFr0mMars commented
boy thats a lot of commits
(ignore my bad github usage pls)

2021-11-18 20:38 UTC, scorbett123 requested changes
1. This should be a plugin, if at all.
2. What on earth is going on with that commit history? 78 commits for a single hud element.
3. Don't push the jar file created.

2021-11-18 20:38 UTC, scorbett123 commented on build.gradle
> -
Why is this line deleted

2021-11-18 20:38 UTC, scorbett123 commented on src/main/kotlin/com/lambda/client/gui/hudgui/elements/misc/Stocks.kt
> +    private var url = "https://finnhub.io/api/v1/quote?symbol=$symbol&token=c5resoqad3ifnpn51ou0"
might as well have this as a local variable.

2021-11-18 20:38 UTC, scorbett123 commented on src/main/kotlin/com/lambda/client/gui/hudgui/elements/misc/Stocks.kt
> +        url = "https://finnhub.io/api/v1/quote?symbol=${symbol.toUpperCase()}&token=c5resoqad3ifnpn51ou0"
Don't commit your api key, its not good practise, really the user should enter their own api key, to prevent rate limiting issues, and unless your paying for this api key I think it is against the finnhub.io TOS.

2021-11-18 20:59 UTC, d1snin commented on src/main/kotlin/com/lambda/client/gui/hudgui/elements/misc/Stocks.kt
> +        url = "https://finnhub.io/api/v1/quote?symbol=${symbol.toUpperCase()}&token=c5resoqad3ifnpn51ou0"
Just make a command to configure this

2021-11-18 21:00 UTC, d1snin commented on src/main/kotlin/com/lambda/client/gui/hudgui/elements/misc/Stocks.kt
> +    private var url = "https://finnhub.io/api/v1/quote?symbol=$symbol&token=c5resoqad3ifnpn51ou0"
might as well have this as const val

2021-11-18 21:12 UTC, czho commented
this should be a plugin and even if we merged this, its like 100 commits for one feature

2021-11-18 23:08 UTC, ItCameFr0mMars commented on build.gradle
> -
it was a for a module that i imported, then removed

2021-11-18 23:11 UTC, ItCameFr0mMars commented on src/main/kotlin/com/lambda/client/gui/hudgui/elements/misc/Stocks.kt
> +        url = "https://finnhub.io/api/v1/quote?symbol=${symbol.toUpperCase()}&token=c5resoqad3ifnpn51ou0"
good idea! I did not think of a command at all!

2021-11-19 17:03 UTC, master7720 commented
add it

2021-11-19 18:06 UTC, czho reviewed
this needs to be a plugin, not in the main client

2021-11-22 18:29 UTC, ItCameFr0mMars commented
Added a warning on enable containing info on how to add an API token.

2021-11-23 07:30 UTC, d1snin commented
> Added a warning on enable containing info on how to add an API token.

Migrate this to a plugin, not a main client feature, [see](https://github.com/lambda-client/lambda/pull/190#pullrequestreview-811517804)

2021-11-23 17:00 UTC, ItCameFr0mMars commented
I made it into a plugin, you can find it here: https://github.com/ItCameFr0mMars/stockticker-plugin

2021-11-23 17:04 UTC, d1snin commented
> I made it into a plugin, you can find it here: https://github.com/ItCameFr0mMars/stockticker-plugin

 ask the maintainer to add this to a plugins then.
You can close this pr

2021-11-23 20:10 UTC, ItCameFr0mMars commented
@Avanatiker 

closing now

2021-11-23 20:10 UTC, closed without merging