Add a warning when KAMI Blue is detected
lambda-client/lambda-legacy pull request #211
Opened 2021-12-27 18:56 UTC by ToxicAven

To prevent incompatibilities

2021-12-27 22:44 UTC, czho approved these changes

2021-12-28 05:29 UTC, huddy987 commented on src/main/kotlin/com/lambda/client/LambdaMod.kt
> +import java.net.URL
is this import needed?

2021-12-28 05:30 UTC, huddy987 approved these changes

2021-12-28 06:06 UTC, huddy987 requested changes

2021-12-28 06:06 UTC, huddy987 commented on src/main/kotlin/com/lambda/client/util/KamiCheck.kt
> +        val kamiCheckList: List<URL> = this.javaClass.classLoader.getResources("org/kamiblue/client/KamiMod.class").toList()
Actually I'm curious, does this also detect KAMI (not KAMI blue)? It would be good to check both the original and blue.

2021-12-28 06:25 UTC, ToxicAven commented on src/main/kotlin/com/lambda/client/util/KamiCheck.kt
> +        val kamiCheckList: List<URL> = this.javaClass.classLoader.getResources("org/kamiblue/client/KamiMod.class").toList()
It does not, however blue and original have become much different from each other, to the point where the overlap would be no different than using more than 1 unrelated client.

2021-12-28 06:38 UTC, huddy987 commented on src/main/kotlin/com/lambda/client/util/KamiCheck.kt
> +        val kamiCheckList: List<URL> = this.javaClass.classLoader.getResources("org/kamiblue/client/KamiMod.class").toList()
ok, makes sense

2021-12-28 06:38 UTC, huddy987 approved these changes

2021-12-28 07:23 UTC, merged