Check hole option for Step module.
lambda-client/lambda-legacy pull request #295
Opened 2022-04-12 00:20 UTC by SnivyLlama

**Describe the pull**
This option allows you to prevent Step from moving you out of a hole.

**Describe how this pull is helpful**
It's useful because Step can accidentally move you out of a hole and then someone can crystal you into oblivion.

**Additional context**
I made it because it pissed me off.

2022-04-12 23:06 UTC, huddy987 commented
There is a compile-time error with your PR. Please resolve it before we can look over your changes
<img width="1003" alt="Screen Shot 2022-04-12 at 5 05 53 PM" src="https://user-images.githubusercontent.com/35442144/163068713-64ebdbc8-8bb0-4783-af2a-02d74dfa29e4.png">

2022-04-12 23:07 UTC, huddy987 requested changes, later dismissed
^^^

2022-04-13 23:46 UTC, SnivyLlama commented
I made a fricking typo... I hate this

2022-04-14 03:09 UTC, Avanatiker approved these changes

2022-04-14 03:13 UTC, merged