Water mark not default
lambda-client/lambda-legacy pull request #30
Opened 2021-04-29 18:16 UTC by Natan515

fix #24

2021-04-29 18:39 UTC, huddy987 requested changes
On line 19 you will need to update closeable so that non-premium users can toggle the watermark

2021-04-29 18:41 UTC, Natan515 commented
Oh, sorry I though it was just changing true to false lol. Will do

2021-04-29 20:12 UTC, huddy987 submitted a review, later dismissed
This looks good, but there is still some strange behavior with the watermark that needs to be investigate (when HUD is disabled if watermark is enabled it is still rendered). I will look into this.

2021-04-29 21:27 UTC, Natan515 commented
It seems good to me

2021-04-29 22:08 UTC, Natan515 commented
I just tried it and it works great

2021-04-30 16:10 UTC, huddy987 requested changes

2021-04-30 16:10 UTC, huddy987 commented on src/main/kotlin/com/lambda/client/gui/hudgui/elements/client/WaterMark.kt
> +    enabledByDefault = false
We should enable the watermark by default

2021-04-30 16:37 UTC, huddy987 approved these changes

2021-04-30 17:34 UTC, Natan515 commented
Dude no! That's the whole thing, that it will be false of default... U want this to be on default but discord rpc no...

2021-04-30 17:35 UTC, Natan515 commented
Pls undo what u did

2021-04-30 20:26 UTC, Avanatiker commented
Works like intended now.

2021-04-30 20:27 UTC, Avanatiker commented
Also @Natan515 pls sign ur commits with GPG in future.

2021-04-30 20:28 UTC, merged

2021-04-30 20:28 UTC, Avanatiker commented
Also can u plase make a new branch for patches and keep master clean? It messes with my git becuase of the similar names

2021-04-30 20:30 UTC, Avanatiker approved these changes

2021-04-30 20:30 UTC, Avanatiker commented on src/main/kotlin/com/lambda/client/gui/hudgui/elements/client/WaterMark.kt
> +    enabledByDefault = false
Should be enabled at least. If player wants he can disable