enh: Add ender chest preview
lambda-client/lambda-legacy pull request #58
Opened 2021-05-03 17:19 UTC by scorbett123

Add ender chest preview to Container preview (renamed from Shulker Preview).

2021-05-03 17:26 UTC, ToxicAven requested changes
Looks pretty good!

2021-05-03 17:26 UTC, ToxicAven commented on src/main/java/com/lambda/client/mixin/client/gui/MixinGuiChest.java
> +            System.out.println("They are here " + lowerChestInventory.getStackInSlot(0));
Remove Logging?

2021-05-03 17:29 UTC, scorbett123 commented on src/main/java/com/lambda/client/mixin/client/gui/MixinGuiChest.java
> +            System.out.println("They are here " + lowerChestInventory.getStackInSlot(0));
Oh, yea, sorry, forgot about that being there.

2021-05-03 17:31 UTC, ToxicAven approved these changes
👍

2021-05-03 20:18 UTC, Natan515 approved these changes

2021-05-03 22:13 UTC, czho approved these changes

2021-05-04 00:07 UTC, Avanatiker approved these changes

2021-05-04 00:07 UTC, merged